# Generated by Django 3.0.8 on 2020-07-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='date_saved',
            new_name='date_created',
        ),
    ]
